package com.example.cliente_app_1.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// CORES DO THEME LIGHT
val primaryLight = Color(0xFF8C4A60)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD9E2)
val onPrimaryContainerLight = Color(0xFF703349)
val secondaryLight = Color(0xFF74565F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD9E2)
val onSecondaryContainerLight = Color(0xFF5A3F47)
val tertiaryLight = Color(0xFF8F4A50)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDADB)
val onTertiaryContainerLight = Color(0xFF72333A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F8)
val onBackgroundLight = Color(0xFF22191C)

// CORES DO THEME DARL
val primaryDark = Color(0xFFFFB1C8)
val onPrimaryDark = Color(0xFF541D32)
val primaryContainerDark = Color(0xFF703349)
val onPrimaryContainerDark = Color(0xFFFFD9E2)
val secondaryDark = Color(0xFFE3BDC6)
val onSecondaryDark = Color(0xFF422931)
val secondaryContainerDark = Color(0xFF5A3F47)
val onSecondaryContainerDark = Color(0xFFFFD9E2)
val tertiaryDark = Color(0xFFFFB2B7)
val onTertiaryDark = Color(0xFF561D24)
val tertiaryContainerDark = Color(0xFF72333A)
val onTertiaryContainerDark = Color(0xFFFFDADB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191113)
val onBackgroundDark = Color(0xFFEFDFE1)